### ISSUE TITLE
Steam Inventory Helper causes inventory fetch timeout

### ISSUE THREAD

**Issue by Bilaboz** [peleicht/backpack-offer-sender#2]
Hello, I noticed that when I have SIH active, it causes inventory fetch timeout.
Disabling SIH solves the issue

**Comment by peleicht** [comment]
Looks like SIH was interfering with some of the logic.
Its fixed in the latest version, thanks for reporting.

**Comment by Bilaboz** [comment]
Thanks for the quick fix!
