### ISSUE TITLE
Button missing on all paints.

### ISSUE THREAD

**Issue by 16546489** [peleicht/backpack-offer-sender#3]

**Comment by 16546489** [comment]
![ScreenShot_20230216182325](https://user-images.githubusercontent.com/106491423/219441026-b09106e5-77f5-40f2-a1a1-2bb0c758badd.png)
Correction its shows on sell orders but not on the bo section.

**Comment by peleicht** [comment]
Looks like they were being ignored due to the paint on them, its fixed in the latest version.
Thanks for reporting!
