### ISSUE TITLE
Next.backpack.tf support issues.

### ISSUE THREAD

**Issue by 16546489** [peleicht/backpack-offer-sender#5]
When using Next.backpack.tf there are major naming differences between the sites. The script correctly gets the names from the listings on both sites but because next cuts out words the script will throw an error. 
Currently I have noticed naming difference with items including these words:
"Taunt:"
"The"
"Non-craftable"
"Paint"
Likely more
This only happens on the buying side because on the seller side we use id's while on the buying site we rely on the name.

Adding to this on the /stats section the naming seems to be on pair with the old site when its in the item information.
The urls seem to contain more on pair information with the sites which could be used to identify correct names on the buyer section.

**Comment by peleicht** [comment]
Thanks for letting me know. This should be fixed with [this commit](https://github.com/peleicht/backpack-offer-sender/commit/4ebe2e99d63aa382450ab307ea3bed076377153c).

I couldn't find any examples of naming differences with "Paint", could you send an example?

**Comment by 16546489** [comment]
Hello sorry for the confusion, paints also had the property of "Non-Craftable" so with that being fixed those as well thanks for the quick hotfix!
