### ISSUE TITLE
Half scrap offers

### ISSUE THREAD

**Issue by 16546489** [peleicht/backpack-offer-sender#6]
Would it be possible to support half scrap listings by rounding it up to the nearest scrap?

**Comment by HavishH** [comment]
@16546489 https://github.com/HavishH/backpack-offer-sender i made a fork that supports this feature

**Comment by peleicht** [comment]
This won't be supported in this version, but there's a fork that does this [here](https://github.com/HavishH/backpack-offer-sender).
